s,@DATADIR@,/usr/share,g
s,@TERMINFO@,/usr/share/terminfo,g
s,@NCURSES_MAJOR@,5,g
s,@NCURSES_MINOR@,7,g
s,@NCURSES_PATCH@,20081102,g
s,@NCURSES_OSPEED@,short,g
s,@CAPTOINFO@,arm-linux-captoinfo,
s,@CLEAR@,arm-linux-clear,
s,@INFOCMP@,arm-linux-infocmp,
s,@INFOTOCAP@,arm-linux-infotocap,
s,@TIC@,arm-linux-tic,
s,@TOE@,arm-linux-toe,
s,@TPUT@,arm-linux-tput,
