/* generated by MKexpanded.sh */
#include <curses.priv.h>
#include <term.h>
#if NCURSES_EXPANDED
 void _nc_toggle_attr_on (attr_t *S, attr_t at)
{
 { if (PAIR_NUMBER(at) > 0) { (*S) = ((*S) & ALL_BUT_COLOR) | (at); } else { (*S) |= (at); } ;};
}
 void _nc_toggle_attr_off (attr_t *S, attr_t at)
{
 { if (PAIR_NUMBER(at) > 0) { (*S) &= ~(at|((((1UL) << 8) - 1UL) << ((0) + 8))); } else { (*S) &= ~(at); } ;};
}
 int _nc_DelCharCost (int count)
{
 return ((_nc_cur_term()->type. Strings[105] != 0) ? _nc_screen()->_dch_cost : ((_nc_cur_term()->type. Strings[21] != 0) ? (_nc_screen()->_dch1_cost * count) : 1000000));
}
 int _nc_InsCharCost (int count)
{
 return ((_nc_cur_term()->type. Strings[108] != 0) ? _nc_screen()->_ich_cost : ((_nc_cur_term()->type. Strings[31] && _nc_cur_term()->type. Strings[42]) ? _nc_screen()->_smir_cost + _nc_screen()->_rmir_cost + (_nc_screen()->_ip_cost * count) : ((_nc_cur_term()->type. Strings[52] != 0) ? ((_nc_screen()->_ich1_cost + _nc_screen()->_ip_cost) * count) : 1000000)));
}
 void _nc_UpdateAttrs (chtype c)
{
 if (!((((*((_nc_screen())->_current_attr))) & (chtype)((~(1UL - 1UL)) << ((0) + 8))) == ((c) & (chtype)((~(1UL - 1UL)) << ((0) + 8))))) vidattr(((c) & (chtype)((~(1UL - 1UL)) << ((0) + 8))));;
}
#else /* ! NCURSES_EXPANDED */
NCURSES_EXPORT(void) _nc_expanded (void) { }
#endif /* NCURSES_EXPANDED */
