# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# This is the auto-Makefile for the uuconf subdirectory of Taylor UUCP.

SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr
exec_prefix = /usr

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = /etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/uucp
pkglibdir = $(libdir)/uucp
pkgincludedir = $(includedir)/uucp
top_builddir = ..

ACLOCAL = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run aclocal
AUTOCONF = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run autoconf
AUTOMAKE = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run automake
AUTOHEADER = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
AMTAR = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run tar
AR = /home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/bin/arm-unknown-linux-uclibcgnueabi-ar
AWK = mawk
CC = /home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc --sysroot=/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir
DEPDIR = .deps
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBOBJS = 
LN_S = ln -s
MAINT = #
NEWCONFIGDIR = ${prefix}/conf/uucp
OBJEXT = o
OLDCONFIGDIR = /usr/lib/uucp
OWNER = uucp
PACKAGE = uucp
POUNDBANG = yes
RANLIB = /home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/bin/arm-unknown-linux-uclibcgnueabi-ranlib
UNIXOBJS = 
VERSION = 1.07
WARN_CFLAGS = -W -Wall -Wstrict-prototypes -Wmissing-prototypes
am__include = include
am__quote = 
install_sh = /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/install-sh

noinst_LIBRARIES = libuuconf.a

libuuconf_a_SOURCES = addblk.c addstr.c allblk.c alloc.c base.c bool.c \
	callin.c calout.c chatc.c cmdarg.c cmdfil.c cmdlin.c cnfnms.c \
	debfil.c deblev.c diacod.c dial.c diasub.c dnams.c errno.c errstr.c \
	filnam.c freblk.c fredia.c free.c freprt.c fresys.c grdcmp.c hdial.c \
	hdnams.c hinit.c hlocnm.c hport.c hrmunk.c hsinfo.c hsnams.c \
	hsys.c hunk.c iniglb.c init.c int.c lckdir.c lineno.c llocnm.c \
	local.c locnm.c logfil.c maxuxq.c mrgblk.c paramc.c port.c \
	prtsub.c pubdir.c rdlocs.c rdperm.c reliab.c remunk.c runuxq.c \
	sinfo.c snams.c split.c spool.c stafil.c strip.c syssub.c \
	tcalou.c tdial.c tdialc.c tdnams.c tgcmp.c thread.c time.c \
	tinit.c tlocnm.c tport.c tportc.c tsinfo.c tsnams.c tsys.c \
	tval.c ugtlin.c unk.c val.c vinit.c vport.c vsinfo.c vsnams.c \
	vsys.c alloc.h syshdr.h uucnfi.h


AM_CFLAGS = -I.. -I$(srcdir)/.. $(WARN_CFLAGS) -DNEWCONFIGLIB=\"$(NEWCONFIGDIR)\" -DOLDCONFIGLIB=\"$(OLDCONFIGDIR)\"
subdir = uuconf
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(noinst_LIBRARIES)

libuuconf_a_AR = $(AR) cru
libuuconf_a_LIBADD =
am_libuuconf_a_OBJECTS = addblk.$(OBJEXT) addstr.$(OBJEXT) \
	allblk.$(OBJEXT) alloc.$(OBJEXT) base.$(OBJEXT) bool.$(OBJEXT) \
	callin.$(OBJEXT) calout.$(OBJEXT) chatc.$(OBJEXT) \
	cmdarg.$(OBJEXT) cmdfil.$(OBJEXT) cmdlin.$(OBJEXT) \
	cnfnms.$(OBJEXT) debfil.$(OBJEXT) deblev.$(OBJEXT) \
	diacod.$(OBJEXT) dial.$(OBJEXT) diasub.$(OBJEXT) \
	dnams.$(OBJEXT) errno.$(OBJEXT) errstr.$(OBJEXT) \
	filnam.$(OBJEXT) freblk.$(OBJEXT) fredia.$(OBJEXT) \
	free.$(OBJEXT) freprt.$(OBJEXT) fresys.$(OBJEXT) \
	grdcmp.$(OBJEXT) hdial.$(OBJEXT) hdnams.$(OBJEXT) \
	hinit.$(OBJEXT) hlocnm.$(OBJEXT) hport.$(OBJEXT) \
	hrmunk.$(OBJEXT) hsinfo.$(OBJEXT) hsnams.$(OBJEXT) \
	hsys.$(OBJEXT) hunk.$(OBJEXT) iniglb.$(OBJEXT) init.$(OBJEXT) \
	int.$(OBJEXT) lckdir.$(OBJEXT) lineno.$(OBJEXT) \
	llocnm.$(OBJEXT) local.$(OBJEXT) locnm.$(OBJEXT) \
	logfil.$(OBJEXT) maxuxq.$(OBJEXT) mrgblk.$(OBJEXT) \
	paramc.$(OBJEXT) port.$(OBJEXT) prtsub.$(OBJEXT) \
	pubdir.$(OBJEXT) rdlocs.$(OBJEXT) rdperm.$(OBJEXT) \
	reliab.$(OBJEXT) remunk.$(OBJEXT) runuxq.$(OBJEXT) \
	sinfo.$(OBJEXT) snams.$(OBJEXT) split.$(OBJEXT) spool.$(OBJEXT) \
	stafil.$(OBJEXT) strip.$(OBJEXT) syssub.$(OBJEXT) \
	tcalou.$(OBJEXT) tdial.$(OBJEXT) tdialc.$(OBJEXT) \
	tdnams.$(OBJEXT) tgcmp.$(OBJEXT) thread.$(OBJEXT) \
	time.$(OBJEXT) tinit.$(OBJEXT) tlocnm.$(OBJEXT) tport.$(OBJEXT) \
	tportc.$(OBJEXT) tsinfo.$(OBJEXT) tsnams.$(OBJEXT) \
	tsys.$(OBJEXT) tval.$(OBJEXT) ugtlin.$(OBJEXT) unk.$(OBJEXT) \
	val.$(OBJEXT) vinit.$(OBJEXT) vport.$(OBJEXT) vsinfo.$(OBJEXT) \
	vsnams.$(OBJEXT) vsys.$(OBJEXT)
libuuconf_a_OBJECTS = $(am_libuuconf_a_OBJECTS)

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = -L/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/lib -L/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/lib
LIBS = -lnsl 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/addblk.Po $(DEPDIR)/addstr.Po \
	$(DEPDIR)/allblk.Po $(DEPDIR)/alloc.Po \
	$(DEPDIR)/base.Po $(DEPDIR)/bool.Po \
	$(DEPDIR)/callin.Po $(DEPDIR)/calout.Po \
	$(DEPDIR)/chatc.Po $(DEPDIR)/cmdarg.Po \
	$(DEPDIR)/cmdfil.Po $(DEPDIR)/cmdlin.Po \
	$(DEPDIR)/cnfnms.Po $(DEPDIR)/debfil.Po \
	$(DEPDIR)/deblev.Po $(DEPDIR)/diacod.Po \
	$(DEPDIR)/dial.Po $(DEPDIR)/diasub.Po \
	$(DEPDIR)/dnams.Po $(DEPDIR)/errno.Po \
	$(DEPDIR)/errstr.Po $(DEPDIR)/filnam.Po \
	$(DEPDIR)/freblk.Po $(DEPDIR)/fredia.Po \
	$(DEPDIR)/free.Po $(DEPDIR)/freprt.Po \
	$(DEPDIR)/fresys.Po $(DEPDIR)/grdcmp.Po \
	$(DEPDIR)/hdial.Po $(DEPDIR)/hdnams.Po \
	$(DEPDIR)/hinit.Po $(DEPDIR)/hlocnm.Po \
	$(DEPDIR)/hport.Po $(DEPDIR)/hrmunk.Po \
	$(DEPDIR)/hsinfo.Po $(DEPDIR)/hsnams.Po \
	$(DEPDIR)/hsys.Po $(DEPDIR)/hunk.Po \
	$(DEPDIR)/iniglb.Po $(DEPDIR)/init.Po \
	$(DEPDIR)/int.Po $(DEPDIR)/lckdir.Po \
	$(DEPDIR)/lineno.Po $(DEPDIR)/llocnm.Po \
	$(DEPDIR)/local.Po $(DEPDIR)/locnm.Po \
	$(DEPDIR)/logfil.Po $(DEPDIR)/maxuxq.Po \
	$(DEPDIR)/mrgblk.Po $(DEPDIR)/paramc.Po \
	$(DEPDIR)/port.Po $(DEPDIR)/prtsub.Po \
	$(DEPDIR)/pubdir.Po $(DEPDIR)/rdlocs.Po \
	$(DEPDIR)/rdperm.Po $(DEPDIR)/reliab.Po \
	$(DEPDIR)/remunk.Po $(DEPDIR)/runuxq.Po \
	$(DEPDIR)/sinfo.Po $(DEPDIR)/snams.Po \
	$(DEPDIR)/split.Po $(DEPDIR)/spool.Po \
	$(DEPDIR)/stafil.Po $(DEPDIR)/strip.Po \
	$(DEPDIR)/syssub.Po $(DEPDIR)/tcalou.Po \
	$(DEPDIR)/tdial.Po $(DEPDIR)/tdialc.Po \
	$(DEPDIR)/tdnams.Po $(DEPDIR)/tgcmp.Po \
	$(DEPDIR)/thread.Po $(DEPDIR)/time.Po \
	$(DEPDIR)/tinit.Po $(DEPDIR)/tlocnm.Po \
	$(DEPDIR)/tport.Po $(DEPDIR)/tportc.Po \
	$(DEPDIR)/tsinfo.Po $(DEPDIR)/tsnams.Po \
	$(DEPDIR)/tsys.Po $(DEPDIR)/tval.Po \
	$(DEPDIR)/ugtlin.Po $(DEPDIR)/unk.Po \
	$(DEPDIR)/val.Po $(DEPDIR)/vinit.Po \
	$(DEPDIR)/vport.Po $(DEPDIR)/vsinfo.Po \
	$(DEPDIR)/vsnams.Po $(DEPDIR)/vsys.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -Os -pipe -Os  -mtune=arm926ej-s -march=armv5te -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/include -I/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/include
DIST_SOURCES = $(libuuconf_a_SOURCES)
DIST_COMMON = README COPYING.LIB Makefile.am Makefile.in
SOURCES = $(libuuconf_a_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
$(srcdir)/Makefile.in: # Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  uuconf/Makefile
Makefile: # $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

AR = ar

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libuuconf.a: $(libuuconf_a_OBJECTS) $(libuuconf_a_DEPENDENCIES) 
	-rm -f libuuconf.a
	$(libuuconf_a_AR) libuuconf.a $(libuuconf_a_OBJECTS) $(libuuconf_a_LIBADD)
	$(RANLIB) libuuconf.a

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/addblk.Po
include $(DEPDIR)/addstr.Po
include $(DEPDIR)/allblk.Po
include $(DEPDIR)/alloc.Po
include $(DEPDIR)/base.Po
include $(DEPDIR)/bool.Po
include $(DEPDIR)/callin.Po
include $(DEPDIR)/calout.Po
include $(DEPDIR)/chatc.Po
include $(DEPDIR)/cmdarg.Po
include $(DEPDIR)/cmdfil.Po
include $(DEPDIR)/cmdlin.Po
include $(DEPDIR)/cnfnms.Po
include $(DEPDIR)/debfil.Po
include $(DEPDIR)/deblev.Po
include $(DEPDIR)/diacod.Po
include $(DEPDIR)/dial.Po
include $(DEPDIR)/diasub.Po
include $(DEPDIR)/dnams.Po
include $(DEPDIR)/errno.Po
include $(DEPDIR)/errstr.Po
include $(DEPDIR)/filnam.Po
include $(DEPDIR)/freblk.Po
include $(DEPDIR)/fredia.Po
include $(DEPDIR)/free.Po
include $(DEPDIR)/freprt.Po
include $(DEPDIR)/fresys.Po
include $(DEPDIR)/grdcmp.Po
include $(DEPDIR)/hdial.Po
include $(DEPDIR)/hdnams.Po
include $(DEPDIR)/hinit.Po
include $(DEPDIR)/hlocnm.Po
include $(DEPDIR)/hport.Po
include $(DEPDIR)/hrmunk.Po
include $(DEPDIR)/hsinfo.Po
include $(DEPDIR)/hsnams.Po
include $(DEPDIR)/hsys.Po
include $(DEPDIR)/hunk.Po
include $(DEPDIR)/iniglb.Po
include $(DEPDIR)/init.Po
include $(DEPDIR)/int.Po
include $(DEPDIR)/lckdir.Po
include $(DEPDIR)/lineno.Po
include $(DEPDIR)/llocnm.Po
include $(DEPDIR)/local.Po
include $(DEPDIR)/locnm.Po
include $(DEPDIR)/logfil.Po
include $(DEPDIR)/maxuxq.Po
include $(DEPDIR)/mrgblk.Po
include $(DEPDIR)/paramc.Po
include $(DEPDIR)/port.Po
include $(DEPDIR)/prtsub.Po
include $(DEPDIR)/pubdir.Po
include $(DEPDIR)/rdlocs.Po
include $(DEPDIR)/rdperm.Po
include $(DEPDIR)/reliab.Po
include $(DEPDIR)/remunk.Po
include $(DEPDIR)/runuxq.Po
include $(DEPDIR)/sinfo.Po
include $(DEPDIR)/snams.Po
include $(DEPDIR)/split.Po
include $(DEPDIR)/spool.Po
include $(DEPDIR)/stafil.Po
include $(DEPDIR)/strip.Po
include $(DEPDIR)/syssub.Po
include $(DEPDIR)/tcalou.Po
include $(DEPDIR)/tdial.Po
include $(DEPDIR)/tdialc.Po
include $(DEPDIR)/tdnams.Po
include $(DEPDIR)/tgcmp.Po
include $(DEPDIR)/thread.Po
include $(DEPDIR)/time.Po
include $(DEPDIR)/tinit.Po
include $(DEPDIR)/tlocnm.Po
include $(DEPDIR)/tport.Po
include $(DEPDIR)/tportc.Po
include $(DEPDIR)/tsinfo.Po
include $(DEPDIR)/tsnams.Po
include $(DEPDIR)/tsys.Po
include $(DEPDIR)/tval.Po
include $(DEPDIR)/ugtlin.Po
include $(DEPDIR)/unk.Po
include $(DEPDIR)/val.Po
include $(DEPDIR)/vinit.Po
include $(DEPDIR)/vport.Po
include $(DEPDIR)/vsinfo.Po
include $(DEPDIR)/vsnams.Po
include $(DEPDIR)/vsys.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`
CCDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-noinstLIBRARIES mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-generic \
	clean-noinstLIBRARIES distclean distclean-compile \
	distclean-depend distclean-generic distclean-tags distdir dvi \
	dvi-am info info-am install install-am install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
