# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# This is the auto-Makefile for the unix subdirectory of Taylor UUCP.

SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr
exec_prefix = /usr

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = /etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/uucp
pkglibdir = $(libdir)/uucp
pkgincludedir = $(includedir)/uucp
top_builddir = ..

ACLOCAL = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run aclocal
AUTOCONF = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run autoconf
AUTOMAKE = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run automake
AUTOHEADER = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
AMTAR = ${SHELL} /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/missing --run tar
AR = /home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/bin/arm-unknown-linux-uclibcgnueabi-ar
AWK = mawk
CC = /home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc --sysroot=/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir
DEPDIR = .deps
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBOBJS = 
LN_S = ln -s
MAINT = #
NEWCONFIGDIR = ${prefix}/conf/uucp
OBJEXT = o
OLDCONFIGDIR = /usr/lib/uucp
OWNER = uucp
PACKAGE = uucp
POUNDBANG = yes
RANLIB = /home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/bin/arm-unknown-linux-uclibcgnueabi-ranlib
UNIXOBJS = 
VERSION = 1.07
WARN_CFLAGS = -W -Wall -Wstrict-prototypes -Wmissing-prototypes
am__include = include
am__quote = 
install_sh = /home/leop/Code/armadeus-4.0/buildroot/output/build/uucp-1.07/install-sh

noinst_LIBRARIES = libunix.a

libunix_a_SOURCES = access.c addbas.c app3.c app4.c basnam.c bytfre.c \
	corrup.c chmod.c cohtty.c cusub.c cwd.c detach.c efopen.c epopen.c \
	exists.c failed.c filnam.c fsusg.c indir.c init.c isdir.c \
	isfork.c iswait.c jobid.c lcksys.c link.c locfil.c lock.c \
	loctim.c mail.c mkdirs.c mode.c move.c opensr.c pause.c \
	picksb.c pipe.c portnm.c priv.c proctm.c recep.c run.c seq.c \
	serial.c signal.c sindir.c size.c sleep.c spawn.c splcmd.c \
	splnam.c spool.c srmdir.c statsb.c status.c sync.c tcp.c \
	time.c tli.c tmpfil.c trunc.c uacces.c ufopen.c uid.c ultspl.c \
	umode.c unknwn.c uuto.c walk.c wldcrd.c work.c xqtfil.c xqtsub.c \
	fsusg.h

libunix_a_LIBADD = $(UNIXOBJS)
EXTRA_libunix_a_SOURCES = getcwd.c mkdir.c rmdir.c dirent.c dup2.c ftw.c \
	remove.c rename.c strerr.c


UUDIRFLAGS = 
#UUDIRFLAGS = -DUUDIR_PROGRAM=\"$(sbindir)/util/uudir\"

AM_CFLAGS = -I.. -I$(srcdir)/.. $(WARN_CFLAGS) $(UUDIRFLAGS) -DSBINDIR=\"$(sbindir)\"
subdir = unix
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(noinst_LIBRARIES)

libunix_a_AR = $(AR) cru
libunix_a_DEPENDENCIES =
am_libunix_a_OBJECTS = access.$(OBJEXT) addbas.$(OBJEXT) app3.$(OBJEXT) \
	app4.$(OBJEXT) basnam.$(OBJEXT) bytfre.$(OBJEXT) \
	corrup.$(OBJEXT) chmod.$(OBJEXT) cohtty.$(OBJEXT) \
	cusub.$(OBJEXT) cwd.$(OBJEXT) detach.$(OBJEXT) efopen.$(OBJEXT) \
	epopen.$(OBJEXT) exists.$(OBJEXT) failed.$(OBJEXT) \
	filnam.$(OBJEXT) fsusg.$(OBJEXT) indir.$(OBJEXT) init.$(OBJEXT) \
	isdir.$(OBJEXT) isfork.$(OBJEXT) iswait.$(OBJEXT) \
	jobid.$(OBJEXT) lcksys.$(OBJEXT) link.$(OBJEXT) \
	locfil.$(OBJEXT) lock.$(OBJEXT) loctim.$(OBJEXT) mail.$(OBJEXT) \
	mkdirs.$(OBJEXT) mode.$(OBJEXT) move.$(OBJEXT) opensr.$(OBJEXT) \
	pause.$(OBJEXT) picksb.$(OBJEXT) pipe.$(OBJEXT) \
	portnm.$(OBJEXT) priv.$(OBJEXT) proctm.$(OBJEXT) \
	recep.$(OBJEXT) run.$(OBJEXT) seq.$(OBJEXT) serial.$(OBJEXT) \
	signal.$(OBJEXT) sindir.$(OBJEXT) size.$(OBJEXT) \
	sleep.$(OBJEXT) spawn.$(OBJEXT) splcmd.$(OBJEXT) \
	splnam.$(OBJEXT) spool.$(OBJEXT) srmdir.$(OBJEXT) \
	statsb.$(OBJEXT) status.$(OBJEXT) sync.$(OBJEXT) tcp.$(OBJEXT) \
	time.$(OBJEXT) tli.$(OBJEXT) tmpfil.$(OBJEXT) trunc.$(OBJEXT) \
	uacces.$(OBJEXT) ufopen.$(OBJEXT) uid.$(OBJEXT) \
	ultspl.$(OBJEXT) umode.$(OBJEXT) unknwn.$(OBJEXT) \
	uuto.$(OBJEXT) walk.$(OBJEXT) wldcrd.$(OBJEXT) work.$(OBJEXT) \
	xqtfil.$(OBJEXT) xqtsub.$(OBJEXT)
libunix_a_OBJECTS = $(am_libunix_a_OBJECTS)

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = -L/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/lib -L/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/lib
LIBS = -lnsl 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/access.Po $(DEPDIR)/addbas.Po \
	$(DEPDIR)/app3.Po $(DEPDIR)/app4.Po \
	$(DEPDIR)/basnam.Po $(DEPDIR)/bytfre.Po \
	$(DEPDIR)/chmod.Po $(DEPDIR)/cohtty.Po \
	$(DEPDIR)/corrup.Po $(DEPDIR)/cusub.Po \
	$(DEPDIR)/cwd.Po $(DEPDIR)/detach.Po \
	$(DEPDIR)/dirent.Po $(DEPDIR)/dup2.Po \
	$(DEPDIR)/efopen.Po $(DEPDIR)/epopen.Po \
	$(DEPDIR)/exists.Po $(DEPDIR)/failed.Po \
	$(DEPDIR)/filnam.Po $(DEPDIR)/fsusg.Po \
	$(DEPDIR)/ftw.Po $(DEPDIR)/getcwd.Po \
	$(DEPDIR)/indir.Po $(DEPDIR)/init.Po \
	$(DEPDIR)/isdir.Po $(DEPDIR)/isfork.Po \
	$(DEPDIR)/iswait.Po $(DEPDIR)/jobid.Po \
	$(DEPDIR)/lcksys.Po $(DEPDIR)/link.Po \
	$(DEPDIR)/locfil.Po $(DEPDIR)/lock.Po \
	$(DEPDIR)/loctim.Po $(DEPDIR)/mail.Po \
	$(DEPDIR)/mkdir.Po $(DEPDIR)/mkdirs.Po \
	$(DEPDIR)/mode.Po $(DEPDIR)/move.Po \
	$(DEPDIR)/opensr.Po $(DEPDIR)/pause.Po \
	$(DEPDIR)/picksb.Po $(DEPDIR)/pipe.Po \
	$(DEPDIR)/portnm.Po $(DEPDIR)/priv.Po \
	$(DEPDIR)/proctm.Po $(DEPDIR)/recep.Po \
	$(DEPDIR)/remove.Po $(DEPDIR)/rename.Po \
	$(DEPDIR)/rmdir.Po $(DEPDIR)/run.Po \
	$(DEPDIR)/seq.Po $(DEPDIR)/serial.Po \
	$(DEPDIR)/signal.Po $(DEPDIR)/sindir.Po \
	$(DEPDIR)/size.Po $(DEPDIR)/sleep.Po \
	$(DEPDIR)/spawn.Po $(DEPDIR)/splcmd.Po \
	$(DEPDIR)/splnam.Po $(DEPDIR)/spool.Po \
	$(DEPDIR)/srmdir.Po $(DEPDIR)/statsb.Po \
	$(DEPDIR)/status.Po $(DEPDIR)/strerr.Po \
	$(DEPDIR)/sync.Po $(DEPDIR)/tcp.Po \
	$(DEPDIR)/time.Po $(DEPDIR)/tli.Po \
	$(DEPDIR)/tmpfil.Po $(DEPDIR)/trunc.Po \
	$(DEPDIR)/uacces.Po $(DEPDIR)/ufopen.Po \
	$(DEPDIR)/uid.Po $(DEPDIR)/ultspl.Po \
	$(DEPDIR)/umode.Po $(DEPDIR)/unknwn.Po \
	$(DEPDIR)/uuto.Po $(DEPDIR)/walk.Po \
	$(DEPDIR)/wldcrd.Po $(DEPDIR)/work.Po \
	$(DEPDIR)/xqtfil.Po $(DEPDIR)/xqtsub.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -Os -pipe -Os  -mtune=arm926ej-s -march=armv5te -mabi=aapcs-linux -msoft-float -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/usr/include -I/home/leop/Code/armadeus-4.0/buildroot/output/build/staging_dir/include
DIST_SOURCES = $(libunix_a_SOURCES) $(EXTRA_libunix_a_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(libunix_a_SOURCES) $(EXTRA_libunix_a_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
$(srcdir)/Makefile.in: # Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  unix/Makefile
Makefile: # $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

AR = ar

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libunix.a: $(libunix_a_OBJECTS) $(libunix_a_DEPENDENCIES) 
	-rm -f libunix.a
	$(libunix_a_AR) libunix.a $(libunix_a_OBJECTS) $(libunix_a_LIBADD)
	$(RANLIB) libunix.a

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/access.Po
include $(DEPDIR)/addbas.Po
include $(DEPDIR)/app3.Po
include $(DEPDIR)/app4.Po
include $(DEPDIR)/basnam.Po
include $(DEPDIR)/bytfre.Po
include $(DEPDIR)/chmod.Po
include $(DEPDIR)/cohtty.Po
include $(DEPDIR)/corrup.Po
include $(DEPDIR)/cusub.Po
include $(DEPDIR)/cwd.Po
include $(DEPDIR)/detach.Po
include $(DEPDIR)/dirent.Po
include $(DEPDIR)/dup2.Po
include $(DEPDIR)/efopen.Po
include $(DEPDIR)/epopen.Po
include $(DEPDIR)/exists.Po
include $(DEPDIR)/failed.Po
include $(DEPDIR)/filnam.Po
include $(DEPDIR)/fsusg.Po
include $(DEPDIR)/ftw.Po
include $(DEPDIR)/getcwd.Po
include $(DEPDIR)/indir.Po
include $(DEPDIR)/init.Po
include $(DEPDIR)/isdir.Po
include $(DEPDIR)/isfork.Po
include $(DEPDIR)/iswait.Po
include $(DEPDIR)/jobid.Po
include $(DEPDIR)/lcksys.Po
include $(DEPDIR)/link.Po
include $(DEPDIR)/locfil.Po
include $(DEPDIR)/lock.Po
include $(DEPDIR)/loctim.Po
include $(DEPDIR)/mail.Po
include $(DEPDIR)/mkdir.Po
include $(DEPDIR)/mkdirs.Po
include $(DEPDIR)/mode.Po
include $(DEPDIR)/move.Po
include $(DEPDIR)/opensr.Po
include $(DEPDIR)/pause.Po
include $(DEPDIR)/picksb.Po
include $(DEPDIR)/pipe.Po
include $(DEPDIR)/portnm.Po
include $(DEPDIR)/priv.Po
include $(DEPDIR)/proctm.Po
include $(DEPDIR)/recep.Po
include $(DEPDIR)/remove.Po
include $(DEPDIR)/rename.Po
include $(DEPDIR)/rmdir.Po
include $(DEPDIR)/run.Po
include $(DEPDIR)/seq.Po
include $(DEPDIR)/serial.Po
include $(DEPDIR)/signal.Po
include $(DEPDIR)/sindir.Po
include $(DEPDIR)/size.Po
include $(DEPDIR)/sleep.Po
include $(DEPDIR)/spawn.Po
include $(DEPDIR)/splcmd.Po
include $(DEPDIR)/splnam.Po
include $(DEPDIR)/spool.Po
include $(DEPDIR)/srmdir.Po
include $(DEPDIR)/statsb.Po
include $(DEPDIR)/status.Po
include $(DEPDIR)/strerr.Po
include $(DEPDIR)/sync.Po
include $(DEPDIR)/tcp.Po
include $(DEPDIR)/time.Po
include $(DEPDIR)/tli.Po
include $(DEPDIR)/tmpfil.Po
include $(DEPDIR)/trunc.Po
include $(DEPDIR)/uacces.Po
include $(DEPDIR)/ufopen.Po
include $(DEPDIR)/uid.Po
include $(DEPDIR)/ultspl.Po
include $(DEPDIR)/umode.Po
include $(DEPDIR)/unknwn.Po
include $(DEPDIR)/uuto.Po
include $(DEPDIR)/walk.Po
include $(DEPDIR)/wldcrd.Po
include $(DEPDIR)/work.Po
include $(DEPDIR)/xqtfil.Po
include $(DEPDIR)/xqtsub.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`
CCDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-noinstLIBRARIES mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-generic \
	clean-noinstLIBRARIES distclean distclean-compile \
	distclean-depend distclean-generic distclean-tags distdir dvi \
	dvi-am info info-am install install-am install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
